### ISSUE TITLE
DRU8-807

### ISSUE THREAD

**Issue by DeveloperPiatt** [osu-wams/madrone#29]
### Todo List
- [x] Create Pull Request
- [x] Rename secondary_menu region to Group Header
- [x] Create a new region for Mobile Group Header
- [x] Set up new region for the block to appear in
- [x] Add block and get suggestions set up for it
- [x] Get the group menu level 0 and 1 to display
- [x] Set up the open/close functionality on the menu
- [ ] Group menu should be a button so we can toggle it with spacebar

### Menu open/close tasks
- [x] Crest menu closes group menu
- [x] Hamburger menu closes group menu
- [x] ESC Key closes group menu
- [x] Make sure the menu closes when other menu's are interacted with

### Style it to match figma
- [x] Menu bar height to 54px
- [x] Bold the font on the group name
- [x] Add padding to the first menu item (~16px)
- [x] Change background to be the dark color
- [x] Update the text to be white
- [x] Expand the menu the full height of the screen
- [x] Add a border
- [x] Add a chevron to make it seem like a drop down menu
- [x] hook up the Menu to toggle the chevron on open/close

### Last Steps
- [x] Merge in 1.x branch
- [x] Clean up code

### Attachments
![group-menu](https://user-images.githubusercontent.com/6465715/111220713-c4e71800-8596-11eb-9ae8-12fbd7351c95.png)

**Comment by DeveloperPiatt** [comment]
There is logic in place in mega-menu.js that is forcing a top style onto the group mega menu. 
```
  const bottomHeader = document
  .querySelector('[role=banner]')
  .getBoundingClientRect().bottom;
  megaMenuDiv.style.top = bottomHeader + 'px';
```

**Comment by DeveloperPiatt** [comment]
Chunk of code that toggles the menu open and closed in mega-menu.js. This is where we need to get away from using lg-tw-grid so we can style it when it's not lg-
```
function setActiveMegaMenu(megaMenuDiv = null, menuIsOpen = false) {
  const openMegaMenus = document.getElementsByClassName(
    'madrone-mega-menu-container lg-tw-grid'
  );

  if (openMegaMenus) {
    for (let i = 0; i < openMegaMenus.length; i++) {
      openMegaMenus[i].classList.remove('lg-tw-grid');
    }
  }

  if (megaMenuDiv && !menuIsOpen) {
    megaMenuDiv.classList.add('lg-tw-grid');
  }
}
```

-- EDIT --

Changing it from lg-tw-grid to tw-grid breaks functionality when it comes to closing/opening mega menus
