### ISSUE TITLE
DRUP8-818: Mega Menu More Menu flash

### ISSUE THREAD

**Issue by DeveloperPiatt** [osu-wams/madrone#32]
### Tasks
- [x] Come up with way to prevent the search from getting pushed off screen while the more menu is still being built.
- [x] Implement to both group and main nav menu (not mobile)

### Issues
- [ ] 1201 x 589 puts the more button on a second line ... 1200 x 589 doesn't do it, and at 1213 x 589 it doesn't do it. But in that small window I'm getting it. Will attack screenshot.
- [x] The container that the menu shows up in wraps, but has no max height set. Need to fix that to prevent it from growing/shrinking

### Attachments
![Screen Shot 2021-03-25 at 2 37 04 PM](https://user-images.githubusercontent.com/6465715/112548315-4437d100-8d79-11eb-8155-e5a402957d8a.png)

![Screen Shot 2021-03-25 at 2 49 30 PM](https://user-images.githubusercontent.com/6465715/112548384-5ca7eb80-8d79-11eb-8a8d-f0e4f95bdf43.png)

**Comment by DeveloperPiatt** [comment]
Solution I came up with for the first pass was to set a height on the grid row to prevent it from growing as the UL grows. I also temp. set the position to absolute so that the search menu doesn't get kicked off screen when a super long titled row enters the mix (see screenshot, 'Another Another Another Big One')

Then we set opacity to 0 so people don't see us building the more menu (which, using this approach, also overflows the content while it's building), and the last step of building the more menu we remove the opacity class and the absolute position.
